version: '2'

services:
  my-yaml_cache_and_website:
    image: mkats/yaml_cache_and_website
    ports:
      # You can replace 8002 with the port on which the website will be available
      - "8002:80"
    restart: always
    environment:
      - SERVICE_LSTN_PORT=28989